baseURL = 'https://ccostes.com/'
languageCode = 'en-us'
title = 'Chris Costes'
theme = 'simple-tailwind'

[params]
images = ['sfo.jpg']
title = 'Chris Costes'
description = "Chris' Blog"
showSummary = 'true'


[markup.goldmark.renderer]
unsafe= true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true